# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >= 4xA100(>40G)
# running time 

# multi-gpu LoRA NOT running zero3

# ACCELERATE_LOG_LEVEL=info 
# accelerate launch 
# --config_file recipes/zero3.yaml 
# --num_processes=3 src/x_r1/grpo.py 
# --config recipes/examples/X_R1_zero_7B_peft_usevllm_witheval_config.yaml
# > ./output/test_7b_lora_sampling.log 2>&1

# Model arguments
model_name_or_path: ./../Qwen/Qwen2.5-1.5b
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: xiaodongguaAIGC/X-R1-750 #  750 / 1500 / 7500
dataset_configs:
- train

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: "auto"
vllm_gpu_memory_utilization: 0.7
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_strategy: every_save
learning_rate: 3.0e-06
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 256
num_generations: 6
max_completion_length: 512
max_steps: -1
num_train_epochs: 1
output_dir: output/X-R1-7B-LoRA
overwrite_output_dir: true
per_device_train_batch_size: 4
push_to_hub: False
report_to:
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1

# GRPO trainer config for evaluate
do_eval: true
eval_strategy: "epoch" # "no", "steps", "epoch"
per_device_eval_batch_size: 16


# lora config
# task_type: model_args.lora_task_type
# lora_in_4bit: True # no support QLoRA
lora_r: 32
lora_target_modules: ["q_proj","v_proj", "k_proj", "embed_tokens"]
lora_alpha: 8
lora_dropout: 0.0
bias: "none"
use_peft: true
